const express = require("express")
const router = express.Router()
const clientController = require("../controllers/clients/clientController")
const verifyOwnership = require("../middlewares/userMiddlewares/verifyOwnership")
const authMiddleware = require("../middlewares/userMiddlewares/authMiddleware")
const negotiationController = require("../controllers/clients/negotiationController")

router.post("/:enterpriseId/clients/add-client", authMiddleware, verifyOwnership, clientController.addClient)
router.get("/:enterpriseId/clients/:clientId", authMiddleware, verifyOwnership, clientController.getClient)
router.get("/:enterpriseId/clients", authMiddleware, verifyOwnership, clientController.getAllClients)
router.put("/:enterpriseId/clients/update-client/:clientId", authMiddleware, verifyOwnership, clientController.updateClient)
router.delete("/:enterpriseId/clients/delete-client/:clientId", authMiddleware, verifyOwnership, clientController.deleteClient)
router.post("/:enterpriseId/clients/:clientId/add-task", authMiddleware, verifyOwnership, clientController.addTaskToClient)
router.get("/:enterpriseId/clients/:clientId/tasks/:taskId", authMiddleware, verifyOwnership, clientController.getTaskToClient)
router.get("/:enterpriseId/clients/:clientId/tasks", authMiddleware, verifyOwnership, clientController.getAllTasksToClient)
router.delete("/:enterpriseId/clients/:clientId/tasks/delete-task/:taskId", authMiddleware, verifyOwnership, clientController.deleteTaskToClient)
router.put("/:enterpriseId/clients/:clientId/tasks/update-task/:taskId", authMiddleware, verifyOwnership, clientController.updateTaskToClient)
router.post("/:enterpriseId/clients/:clientId/add-negotiation", authMiddleware, negotiationController.addNegotiation)
router.get("/:enterpriseId/clients/:clientId/negotiations/:negotiationId", authMiddleware, negotiationController.getNegotiation)
router.get("/:enterpriseId/clients/:clientId/negotitations", authMiddleware, negotiationController.getAllNegotiations)
router.delete("/:enterpriseId/clients/:clientId/negotiations/delete-negotiation/:negotiationId", authMiddleware, negotiationController.deleteNegotiation)
router.delete("/:enterpriseId/clients/:clientId/negotiations/delete-all", authMiddleware, negotiationController.deleteAllNegotiations)
router.put("/:enterpriseId/clients/:clientId/negotiations/update-negotiation/:negotiationId", authMiddleware, negotiationController.updateNegotiation)
router.get("/:enterpriseId/clients/:clientId/negotiations/filter/by-status", authMiddleware, negotiationController.filterNegotiationsByStatus)
router.get("/:enterpriseId/clients/:clientId/negotiations/filter/by-expecting-close-date", authMiddleware, negotiationController.filterNegotiationsByExpectingCloseDate)

module.exports = router