const express = require("express")
const router = express.Router()
const authMiddleware = require("../middlewares/userMiddlewares/authMiddleware")
const incomeController = require("../controllers/finance/incomeController")
const expenseController = require("../controllers/finance/expenseController")
const activeController = require("../controllers/finance/activeController")
const passiveController = require("../controllers/finance/passiveController")
const netWorthController = require("../controllers/finance/netWorthController")
const cashFlowController = require("../controllers/finance/cashFlowController")
const verifyOwnership = require("../middlewares/userMiddlewares/verifyOwnership")

router.post("/:enterpriseId/finances/add-income", authMiddleware, verifyOwnership, incomeController.addIncome)
router.post("/:enterpriseId/finances/add-expense", authMiddleware, verifyOwnership, expenseController.addExpense)
router.post("/:enterpriseId/finances/add-active", authMiddleware, verifyOwnership, activeController.addActive)
router.post("/:enterpriseId/finances/add-passive", authMiddleware, verifyOwnership, passiveController.addPassive)
router.get("/:enterpriseId/finances/incomes", authMiddleware, verifyOwnership, incomeController.getIncomes)
router.get("/:enterpriseId/finances/expenses", authMiddleware, verifyOwnership, expenseController.getExpenses)
router.get("/:enterpriseId/finances/actives", authMiddleware, verifyOwnership, activeController.getActives)
router.get("/:enterpriseId/finances/liabilities", authMiddleware, verifyOwnership, passiveController.getLiabilities)
router.get("/:enterpriseId/finances/cash-flow", authMiddleware, verifyOwnership, cashFlowController.getCashFlow)
router.get("/:enterpriseId/finances/net-worth", authMiddleware, verifyOwnership, netWorthController.getNetWorth)
router.get("/:enterpriseId/finances/incomes/by-date", authMiddleware, verifyOwnership, incomeController.getIncomesByDate)
router.get("/:enterpriseId/finances/expenses/by-date", authMiddleware, verifyOwnership, expenseController.getExpensesByDate)
router.get("/:enterpriseId/finances/actives/by-date", authMiddleware, verifyOwnership, activeController.getActivesByDate)
router.get("/:enterpriseId/finances/liabilities/by-date", authMiddleware, verifyOwnership, passiveController.getLiabilitiesByDate)
router.get("/:enterpriseId/finances/cash-flow/by-date", authMiddleware, verifyOwnership, cashFlowController.getCashFlowByDate)
router.get("/:enterpriseId/finances/net-worth/by-date", authMiddleware, verifyOwnership, netWorthController.getNetWorthByDate)
router.get("/:enterpriseId/finances/incomes/by-month", authMiddleware, verifyOwnership, incomeController.getIncomesByMonth)
router.get("/:enterpriseId/finances/expenses/by-month", authMiddleware, verifyOwnership, expenseController.getExpensesByMonth)
router.get("/:enterpriseId/finances/actives/by-month", authMiddleware, verifyOwnership, activeController.getActivesByMonth)
router.get("/:enterpriseId/finances/liabilities/by-month", authMiddleware, verifyOwnership, passiveController.getLiabilitiesByMonth)
router.get("/:enterpriseId/finances/incomes/by-current-month", authMiddleware, verifyOwnership, incomeController.getIncomesByCurrentMonth)
router.get("/:enterpriseId/finances/expenses/by-current-month", authMiddleware, verifyOwnership, expenseController.getExpensesByCurrentMonth)
router.get("/:enterpriseId/finances/actives/by-current-month", authMiddleware, verifyOwnership, activeController.getActivesByCurrentMonth)
router.get("/:enterpriseId/finances/liabilities/by-current-month", authMiddleware, verifyOwnership, passiveController.getLiabilitiesByCurrentMonth)
router.get("/:enterpriseId/finances/cash-flow/by-current-month", authMiddleware, verifyOwnership, cashFlowController.getCashFlowByCurrentMonth)
router.get("/:enterpriseId/finances/net-worth/by-current-month", authMiddleware, verifyOwnership, netWorthController.getNetWorthByCurrentMonth)
router.get("/:enterpriseId/finances/incomes/by-current-date", authMiddleware, verifyOwnership, incomeController.getIncomesByCurrentDate)
router.get("/:enterpriseId/finances/expenses/by-current-date", authMiddleware, verifyOwnership, expenseController.getExpensesByCurrentDate)
router.get("/:enterpriseId/finances/actives/by-current-date", authMiddleware, verifyOwnership, activeController.getActivesByCurrentDate)
router.get("/:enterpriseId/finances/liabilities/by-current-date", authMiddleware, verifyOwnership, passiveController.getLiabilitiesByCurrentDate)
router.get("/:enterpriseId/finances/cash-flow/by-current-date", authMiddleware, verifyOwnership, cashFlowController.getCashFlowByCurrentDate)
router.get("/:enterpriseId/finances/net-worth/by-current-date", authMiddleware, verifyOwnership, netWorthController.getNetWorthByCurrentDate)
router.get("/:enterpriseId/finances/incomes/by-current-year", authMiddleware, verifyOwnership, incomeController.getIncomesByCurrentYear)
router.get("/:enterpriseId/finances/expenses/by-current-year", authMiddleware, verifyOwnership, expenseController.getExpensesByCurrentYear)
router.get("/:enterpriseId/finances/actives/by-current-year", authMiddleware, verifyOwnership, activeController.getActivesByCurrentYear)
router.get("/:enterpriseId/finances/liabilities/by-current-year", authMiddleware, verifyOwnership, passiveController.getLiabilitiesByCurrentYear)
router.get("/:enterpriseId/finances/cash-flow/by-current-year", authMiddleware, verifyOwnership, cashFlowController.getCashFlowByCurrentYear)
router.get("/:enterpriseId/finances/net-worth/by-current-year", authMiddleware, verifyOwnership, netWorthController.getNetWorthByCurrentYear)
router.put("/:enterpriseId/finances/incomes/update/:elementId", authMiddleware, verifyOwnership, incomeController.updateIncome)
router.put("/:enterpriseId/finances/expenses/update/:elementId", authMiddleware, verifyOwnership, expenseController.updateExpense)
router.put("/:enterpriseId/finances/actives/update/:activeId", authMiddleware, verifyOwnership, activeController.updateActive)
router.put("/:enterpriseId/finances/liabilities/update/:passiveId", authMiddleware, verifyOwnership, passiveController.updatePassive)
router.delete("/:enterpriseId/finances/incomes/delete/:elementId", authMiddleware, verifyOwnership, incomeController.deleteIncome)
router.delete("/:enterpriseId/finances/expenses/delete/:elementId", authMiddleware, verifyOwnership, expenseController.deleteExpense)
router.delete("/:enterpriseId/finances/actives/delete/:activeId", authMiddleware, verifyOwnership, activeController.deleteActive)
router.delete("/:enterpriseId/finances/liabilities/delete/:passiveId", authMiddleware, verifyOwnership, passiveController.deletePassive)
router.get("/:enterpriseId/finances/incomes/projection-next-date", incomeController.projectionIncomesInNextDate)
router.get("/:enterpriseId/finances/incomes/projection-next-month", incomeController.projectionIncomesInNextMonth)
router.get("/:enterpriseId/finances/incomes/projection-next-year", incomeController.projectionIncomesInNextYear)
router.get("/:enterpriseId/finances/expenses/projection-next-date", expenseController.projectionExpensesInNextDate)
router.get("/:enterpriseId/finances/expenses/projection-next-month", expenseController.projectionExpensesInNextMonth)
router.get("/:enterpriseId/finances/expenses/projection-next-year", expenseController.projectionExpensesInNextYear)
router.get("/:enterpriseId/finances/cash-flow/projection-next-date", cashFlowController.projectionCashFlowInNextDate)
router.get("/:enterpriseId/finances/cash-flow/projection-next-month", cashFlowController.projectionCashFlowInNextMonth)
router.get("/:enterpriseId/finances/cash-flow/projection-next-year", cashFlowController.projectionCashFlowInNextYear)

module.exports = router