const express = require("express")
const router = express.Router()
const authMiddleware = require("../middlewares/userMiddlewares/authMiddleware")
const recoveryKeyController = require("../controllers/security/recoveryKey/recoveryKeyController")
const suspiciousLoginController = require("../controllers/security/suspiciousLogin/suspiciousLoginController")
const twoFAController = require("../controllers/security/2FA/2FAController")
const exportDataController = require("../controllers/security/data/exportDataController")
const setChangesOf2FA = require("../controllers/handlers/security/2FA/setChangesOf2FA")
const setChangesOfPassword = require("../controllers/handlers/security/password/setChangesOfPassword")
const setChangesOfSuspiciousLogin = require("../controllers/handlers/security/suspiciousLogin/setChangesOfSuspiciousLogin")

router.post("/:userId/recovery-key/add-recovery-key", authMiddleware, recoveryKeyController.addRecoveryKey)
router.get("/:userId/recovery-key/get-recovery-key", authMiddleware, recoveryKeyController.getRecoveryKey)
router.put("/:userId/suspicious-logins/:suspiciousLoginId/update-suspicious-login", authMiddleware, suspiciousLoginController.setActionByUserSuspiciousLogin)
router.get("/:userId/suspicious-logins/:suspiciousLoginId", authMiddleware, suspiciousLoginController.getSuspiciousLogin)
router.get("/:userId/suspicious-logins", authMiddleware, suspiciousLoginController.getAllSuspiciousLogins)
router.post("/:userId/suspicious-logins/status", authMiddleware, setChangesOfSuspiciousLogin)
router.put("/:userId/activate-or-desactivate-2fa", authMiddleware, twoFAController.activeOInactiveVerify2FA)
router.put("/:userId/confirm-2fa-status", authMiddleware, setChangesOf2FA)
router.put("/:userId/confirm-update-password", authMiddleware, setChangesOfPassword)
router.get("/:userId/export-data/csv", authMiddleware, exportDataController.exportCSVData)
router.get("/:userId/export-data/json", authMiddleware, exportDataController.exportJSONData)
router.get("/:userId/export-logs/csv", authMiddleware, exportDataController.exportLogsCSV)

module.exports = router