const express = require("express")
const router = express.Router()
const sustainableEmployeeController = require("../controllers/rrhh/sustainableRrhhController")
const certificationController = require("../controllers/rrhh/sustainable/certificationController")
const initiativeController = require("../controllers/rrhh/sustainable/initiativeController")
const sustainabilityObjectiveController = require("../controllers/rrhh/sustainable/sustainabilityObjectiveController")
const reportController = require("../controllers/rrhh/sustainable/reportController")
const authMiddleware = require("../middlewares/userMiddlewares/authMiddleware")
const verifyOwnership = require("../middlewares/userMiddlewares/verifyOwnership")

router.post("/:enterpriseId/employees/:employeeId/add-certification", /*authMiddleware, verifyOwnership,*/ certificationController.addCertification)
router.get("/:enterpriseId/employees/:employeeId/certifications/:certificationId", authMiddleware, verifyOwnership, certificationController.getCertification)
router.get("/:enterpriseId/employees/:employeeId/certifications", authMiddleware, verifyOwnership, certificationController.getAllCertifications)
router.put("/:enterpriseId/employees/:employeeId/certifications/update-certification/:certificationId", authMiddleware, verifyOwnership, certificationController.updateCertification)
router.delete("/:enterpriseId/employees/:employeeId/certifications/delete-certification/:certificationId", authMiddleware, verifyOwnership, certificationController.deleteCertification)
router.delete("/:enterpriseId/employees/:employeeId/certifications/delete-all", certificationController.deleteAllCertifications)
router.get("/:enterpriseId/employees/:employeeId/certifications/filter/by-date", authMiddleware, verifyOwnership, certificationController.getCertificationsByDate)
router.post("/:enterpriseId/employees/:employeeId/add-initiative",/* authMiddleware, verifyOwnership,*/ initiativeController.addInitiative)
router.get("/:enterpriseId/employees/:employeeId/initiatives/:initiativeId", authMiddleware, verifyOwnership, initiativeController.getInitiative)
router.get("/:enterpriseId/employees/:employeeId/initiatives", authMiddleware, verifyOwnership, initiativeController.getAllInitiatives)
router.put("/:enterpriseId/employees/:employeeId/initiatives/update-initiative/:initiativeId", authMiddleware, verifyOwnership, initiativeController.updateInitiative)
router.delete("/:enterpriseId/employees/:employeeId/initiatives/delete-initiative/:initiativeId", authMiddleware, verifyOwnership, initiativeController.deleteInitiative)
router.delete("/:enterpriseId/employees/:employeeId/initiatives/delete-all", /*authMiddleware, verifyOwnership,*/ initiativeController.deleteAllInitiatives)
router.get("/:enterpriseId/employees/:employeeId/initiatives/filter/by-date", authMiddleware, verifyOwnership, initiativeController.getInitiativesByDate)
router.post("/:enterpriseId/employees/:employeeId/add-sustainability-objective", authMiddleware, verifyOwnership, sustainabilityObjectiveController.addSustainabilityObjective)
router.get("/:enterpriseId/employees/:employeeId/sustainability-objectives/:sustainabilityObjectiveId", authMiddleware, verifyOwnership, sustainabilityObjectiveController.getSustainabilityObjective)
router.get("/:enterpriseId/employees/:employeeId/sustainability-objectives", authMiddleware, verifyOwnership, sustainabilityObjectiveController.getAllSustainabilityObjectives)
router.put("/:enterpriseId/employees/:employeeId/sustainability-objectives/update-sustainability-objective/:sustainabilityObjectiveId", authMiddleware, verifyOwnership, sustainabilityObjectiveController.updateSustainabilityObjective)
router.delete("/:enterpriseId/employees/:employeeId/sustainability-objectives/delete-sustainability-objective/:sustainabilityObjectiveId", authMiddleware, verifyOwnership, sustainabilityObjectiveController.deleteSustainabilityObjective)
router.delete("/:enterpriseId/employees/:employeeId/sustainability-objectives/delete-all", authMiddleware, verifyOwnership, sustainabilityObjectiveController.deleteSustainabilityObjective)
router.post("/:enterpriseId/employees/:employeeId/assists/:assistId/add-report", reportController.addReport)
router.get("/:enterpriseId/employees/:employeeId/assists/:assistId/reports/:reportId", authMiddleware, verifyOwnership, reportController.getReport)
router.get("/:enterpriseId/employees/:employeeId/assists/:assistId/reports/", authMiddleware, verifyOwnership, reportController.getAllReports)
router.put("/:enterpriseId/employees/:employeeId/assists/:assistId/reports/update-report/:reportId", reportController.updateReport)
router.delete("/:enterpriseId/employees/:employeeId/assists/:assistId/reports/delete-report/:reportId", reportController.deleteReport)
router.get("/:enterpriseId/employees/:employeeId/carbon-footprint/by-current-month", authMiddleware, verifyOwnership, sustainableEmployeeController.getCarbonFootprintByCurrentMonth)
router.get("/:enterpriseId/employees/:employeeId/carbon-footprint/by-current-year", authMiddleware, verifyOwnership, sustainableEmployeeController.getCarbonFootprintByCurrentYear)
router.get("/:enterpriseId/employees/:employeeId/carbon-footprint/by-current-week", authMiddleware, verifyOwnership, sustainableEmployeeController.getCarbonFootprintByCurrentWeek)
router.get("/:enterpriseId/employees/:employeeId/carbon-footprint/by-customer-date", authMiddleware, verifyOwnership, sustainableEmployeeController.getCarbonFootprintByCustomDate)
router.get("/:enterpriseId/employees/:employeeId/carbon-footprint/compare/by-last-year", sustainableEmployeeController.compareCarbonFootprintByLastYear)
router.get("/:enterpriseId/employees/:employeeId/carbon-footprint/compare/by-last-month", sustainableEmployeeController.compareCarbonFootprintByLastMonth)
router.get("/:enterpriseId/employees/:employeeId/carbon-footprint/compare/by-last-date", sustainableEmployeeController.compareCarbonFootprintByLastDate)
router.get("/:enterpriseId/employees/:employeeId/carbon-footprint/compare/by-last-week", sustainableEmployeeController.compareCarbonFootprintByLastWeek)
router.get("/:enterpriseId/employees/:employeeId/consumption-kwh/compare/by-last-year", sustainableEmployeeController.compareKwhConsumptionInLastYear)
router.get("/:enterpriseId/employees/:employeeId/consumption-kwh/compare/by-last-month", sustainableEmployeeController.compareKwhConsumptionInLastMonth)
router.get("/:enterpriseId/employees/:employeeId/consumption-kwh/compare/by-last-date", sustainableEmployeeController.compareKwhConsumptionInLastDate)
router.get("/:enterpriseId/employees/:employeeId/consumption-kwh/compare/by-last-week", sustainableEmployeeController.compareKwhConsumptionInLastWeek)
router.get("/:enterpriseId/employees/:employeeId/waste-generated/compare/by-last-year", sustainableEmployeeController.compareWasteGeneratedInLastYear)
router.get("/:enterpriseId/employees/:employeeId/waste-generated/compare/by-last-month", sustainableEmployeeController.compareWasteGeneratedInLastMonth)
router.get("/:enterpriseId/employees/:employeeId/waste-generated/compare/by-last-date", sustainableEmployeeController.compareWasteGeneratedInLastDate)
router.get("/:enterpriseId/employees/:employeeId/waste-generated/compare/by-last-week", sustainableEmployeeController.compareWasteGeneratedInLastWeek)

module.exports = router