const express = require("express")
const router = express.Router()
const sustainablePoliticController = require("../controllers/sustainability/sustainablePoliticController")
const sustainableTaskController = require("../controllers/sustainability/sustainableTaskController")
const sustainableObjectiveController = require("../controllers/sustainability/sustainableObjectiveController")
const auditController = require("../controllers/sustainability/auditController")
const legalRequirementController = require("../controllers/sustainability/legalRequirementController")
const authMiddleware = require("../middlewares/userMiddlewares/authMiddleware")
const roleMiddleware = require("../middlewares/userMiddlewares/roleMiddleware")
const verifyOwnership = require("../middlewares/userMiddlewares/verifyOwnership")

router.post("/:enterpriseId/sustainability/add-sustainable-politic", authMiddleware, roleMiddleware("Administrador", "Miembro del equipo"), sustainablePoliticController.addSustainablePolitic)
router.get("/:enterpriseId/sustainability/sustainable-politics/:sustainablePoliticId", sustainablePoliticController.getSustainablePolitic)
router.get("/:enterpriseId/sustainability/sustainable-politics", sustainablePoliticController.getAllSustainablePolitics)
router.put("/:enterpriseId/sustainability/sustainable-politics/update-sustainable-politic/:sustainablePoliticId", sustainablePoliticController.updateSustainablePolitic)
router.delete("/:enterpriseId/sustainability/sustainable-politics/delete-sustainable-politic/:sustainablePoliticId", sustainablePoliticController.deleteSustainablePolitic)
router.delete("/:enterpriseId/sustainability/sustainable-politics/delete-all", sustainablePoliticController.deleteAllSustainablePolitics)
router.get("/:enterpriseId/sustainability/sustainable-politics/filter/by-date", sustainablePoliticController.filterSustainablePoliticsByDate)
router.get("/:enterpriseId/sustainability/sustainable-politics/filter/by-last-revision", sustainablePoliticController.filterSustainablePoliticsByLastRevisionDate)
router.post("/:enterpriseId/sustainability/add-sustainable-task", sustainableTaskController.addSustainableTask)
router.get("/:enterpriseId/sustainability/sustainable-tasks/:sustainableTaskId", sustainableTaskController.getSustainableTask)
router.get("/:enterpriseId/sustainability/sustainable-tasks", sustainableTaskController.getAllSustainableTasks)
router.put("/:enterpriseId/sustainability/sustainable-tasks/update-sustainable-task/:sustainableTaskId", sustainableTaskController.updateSustainableTask)
router.delete("/:enterpriseId/sustainability/sustainable-tasks/delete-sustainable-task/:sustainableTaskId", sustainableTaskController.deleteSustainableTask)
router.delete("/:enterpriseId/sustainability/sustainable-tasks/delete-all", sustainableTaskController.deleteAllSustainableTasks)
router.get("/:enterpriseId/sustainability/sustainable-tasks/filter/by-custom-date", sustainableTaskController.filterSustainableTasksByCustomDate)
router.get("/:enterpriseId/sustainability/sustainable-tasks/filter/by-start-date", sustainableTaskController.filterSustainableTasksByStartDate)
router.get("/:enterpriseId/sustainability/sustainable-tasks/filter/by-end-date", sustainableTaskController.filterSustainableTasksByEndDate)
router.get("/:enterpriseId/sustainability/sustainable-tasks/filter/by-impact", sustainableTaskController.filterSustainableTasksByImpact)
router.get("/:enterpriseId/sustainability/sustainable-tasks/filter/by-phase", sustainableTaskController.filterSustainableTasksByPhase)
//objetivos sustentables
router.post("/:enterpriseId/sustainability/add-sustainable-objective", authMiddleware, verifyOwnership, sustainableObjectiveController.addSustainableObjective)
router.get("/:enterpriseId/sustainability/sustainable-objectives/:sustainableObjectiveId", sustainableObjectiveController.getSustainableObjective)
router.get("/:enterpriseId/sustainability/sustainable-objectives", sustainableObjectiveController.getAllSustainableObjectives)
router.put("/:enterpriseId/sustainability/sustainable-objectives/update-sustainable-objective/:sustainableObjectiveId", sustainableObjectiveController.updateSustainableObjective)
router.delete("/:enterpriseId/sustainability/sustainable-objectives/delete-sustainable-objective/:sustainableObjectiveId", sustainableObjectiveController.deleteSustainableObjective)
router.delete("/:enterpriseId/sustainability/sustainable-objectives/delete-all", sustainableObjectiveController.deleteAllSustainableObjectives)
router.get("/:enterpriseId/sustainability/sustainable-objectives/filter/by-date", sustainableObjectiveController.filterSustainableObjectivesByDate)
router.get("/:enterpriseId/sustainability/sustainable-objectives/filter/by-status", sustainableObjectiveController.filterSustainableObjectivesByStatus)
router.get("/:enterpriseId/sustainability/sustainable-objectives/filter/by-impact", sustainableObjectiveController.filterSustainableObjectivesByImpact)
router.get("/:enterpriseId/sustainability/sustainable-objectives/filter/by-ODS-relationship", sustainableObjectiveController.filterSustainableObjectivesByODSrelationship)
//auditorias
router.post("/:enterpriseId/sustainability/add-audit", authMiddleware, roleMiddleware("Administrador", "Miembro del equipo"), auditController.addAudit)
router.get("/:enterpriseId/sustainability/audits/:auditId", auditController.getAudit)
router.get("/:enterpriseId/sustainability/audits", auditController.getAllAudits)
router.put("/:enterpriseId/sustainability/audits/update-audit/:auditId", auditController.updateAudit)
router.delete("/:enterpriseId/sustainability/audits/delete-audit/:auditId", auditController.deleteAudit)
router.delete("/:enterpriseId/sustainability/audits/delete-all", auditController.deleteAllAudits)
router.get("/:enterpriseId/sustainability/audits/filter/by-date", auditController.filterAuditsByDate)
router.get("/:enterpriseId/sustainability/audits/filter/by-custom-date", auditController.filterAuditsByCustomDates)
router.get("/:enterpriseId/sustainability/audits/filter/by-current-week", auditController.filterAuditsByCurrentWeek)
router.get("/:enterpriseId/sustainability/audits/filter/by-current-month", auditController.filterAuditsByCurrentMonth)
router.get("/:enterpriseId/sustainability/audits/filter/by-current-year", auditController.filterAuditsByCurrentYear)
//requisitos legales
router.post("/:enterpriseId/sustainability/add-legal-requirement", legalRequirementController.addLegalRequirement)
router.get("/:enterpriseId/sustainability/legal-requirements/:legalRequirementId", legalRequirementController.getLegalRequirement)
router.get("/:enterpriseId/sustainability/legal-requirements", legalRequirementController.getAllLegalRequirements)
router.put("/:enterpriseId/sustainability/legal-requirements/update-legal-requirement/:legalRequirementId", legalRequirementController.updateLegalRequirement)
router.delete("/:enterpriseId/sustainability/legal-requirements/delete-legal-requirement/:legalRequirementId", legalRequirementController.deleteLegalRequirement)
router.delete("/:enterpriseId/sustainability/legal-requirements/delete-all", legalRequirementController.deleteAllLegalRequirements)
router.get("/:enterpriseId/sustainability/legal-requirements/filter/by-compliance-status", legalRequirementController.filterLegalRequirementsByComplianceStatus)
router.get("/:enterpriseId/sustainability/legal-requirements/filter/by-regulatory-authority", legalRequirementController.filterLegalRequirementsByRegulatoryAuthority)

module.exports = router