const express = require("express")
const router = express.Router()
const hardwareController = require("../controllers/technology/hardware/hardwareController")
const softwareController = require("../controllers/technology/software/softwareController")
const updateManagementController = require("../controllers/technology/software/updateManagementController")
const securityUpdateController = require("../controllers/technology/software/securityUpdateController")
const licenseManagementController = require("../controllers/technology/software/licenseManagementController")
const supportController = require("../controllers/technology/software/supportController")
const maintenanceController = require("../controllers/technology/hardware/maintenanceController")
const useController = require("../controllers/technology/hardware/useController")

router.post("/:enterpriseId/technology/hardwares/add-hardware", hardwareController.addHardware)
router.get("/:enterpriseId/technology/hardwares/:hardwareId", hardwareController.getHardware)
router.get("/:enterpriseId/technology/hardwares", hardwareController.getAllHardwares)
router.put("/:enterpriseId/technology/hardwares/update-hardware/:hardwareId", hardwareController.updateHardware)
router.delete("/:enterpriseId/technology/hardwares/delete-hardware/:hardwareId", hardwareController.deleteHardware)
router.delete("/:enterpriseId/technology/hardwares/delete-all", hardwareController.deleteAllHardwares)
router.get("/:enterpriseId/technology/hardwares/filter/by-type", hardwareController.getHardwaresByType)
router.get("/:enterpriseId/technology/hardwares/filter/by-manufacturer", hardwareController.getHardwaresByManufacturer)
router.post("/:enterpriseId/technology/hardwares/:hardwareId/add-maintenance", maintenanceController.addMaintenance)
router.get("/:enterpriseId/technology/hardwares/:hardwareId/maintenances/:maintenanceId", maintenanceController.getMaintenance)
router.get("/:enterpriseId/technology/hardwares/:hardwareId/maintenances", maintenanceController.getAllMaintenances)
router.put("/:enterpriseId/technology/hardwares/:hardwareId/maintenances/update-maintenance/:maintenanceId", maintenanceController.updateMaintenance)
router.delete("/:enterpriseId/technology/hardwares/:hardwareId/maintenances/delete-maintenance/:maintenanceId", maintenanceController.deleteMaintenance)
router.delete("/:enterpriseId/technology/hardwares/:hardwareId/maintenances/delete-all", maintenanceController.deleteAllMaintenances)
router.get("/:enterpriseId/technology/hardwares/:hardwareId/maintenances/filter/by-custom-date", maintenanceController.getMaintenancesByCustomDate)
router.post("/:enterpriseId/technology/hardwares/:hardwareId/add-use", useController.addUse)
router.get("/:enterpriseId/technology/hardwares/:hardwareId/uses/:useId", useController.getUse)
router.get("/:enterpriseId/technology/hardwares/:hardwareId/uses", useController.getAllUses)
router.put("/:enterpriseId/technology/hardwares/:hardwareId/uses/update-use/:useId", useController.updateUse)
router.delete("/:enterpriseId/technology/hardwares/:hardwareId/uses/delete-use/:useId", useController.deleteUse)
router.delete("/:enterpriseId/technology/hardwares/:hardwareId/uses/delete-all", useController.deleteAllUses)
router.get("/:enterpriseId/technology/hardwares/:hardwareId/uses/filter/by-customer-date", useController.getUsesByCustomDate)
router.get("/:enterpriseId/technology/hardwares/:hardwareId/uses/filter/by-employee", useController.getUsesByEmployee)
/* Aca comienza la parte software
-
-
-
-
-
*/
router.post("/:enterpriseId/technology/softwares/add-software", softwareController.addSoftware)
router.get("/:enterpriseId/technology/softwares/:softwareId", softwareController.getSoftware)
router.get("/:enterpriseId/technology/softwares", softwareController.getAllSoftwares)
router.put("/:enterpriseId/technology/softwares/update-software/:softwareId", softwareController.updateSoftware)
router.delete("/:enterpriseId/technology/softwares/delete-software/:softwareId", softwareController.deleteSoftware)
router.delete("/:enterpriseId/technology/softwares/delete-all", softwareController.deleteAllSoftwares)
router.get("/:enterpriseId/technology/softwares/filter/by-vendor", softwareController.getSoftwaresByVendor)
router.get("/:enterpriseId/technology/softwares/filter/by-status", softwareController.getSoftwaresByStatus)
router.post("/:enterpriseId/technology/softwares/:softwareId/add-update-management", updateManagementController.addUpdateManagement)
router.get("/:enterpriseId/technology/softwares/:softwareId/update-managements/:updateManagementId", updateManagementController.getUpdateManagement)
router.get("/:enterpriseId/technology/softwares/:softwareId/update-managements", updateManagementController.getAllUpdateManagements)
router.put("/:enterpriseId/technology/softwares/:softwareId/update-managements/update-update-management/:updateManagementId", updateManagementController.updateUpdateManagement)
router.delete("/:enterpriseId/technology/softwares/:softwareId/update-managements/delete-update-management/:updateManagementId", updateManagementController.deleteUpdateManagement)
router.delete("/:enterpriseId/technology/softwares/:softwareId/update-managements/delete-all", updateManagementController.deleteAllUpdateManagements)
router.get("/:enterpriseId/technology/softwares/:softwareId/update-managements/filter/by-custom-date", updateManagementController.getUpdateManagementsByCustomDate)
router.get("/:enterpriseId/technology/softwares/:softwareId/update-managements/filter/by-current-year", updateManagementController.getUpdateManagementsByCurrentYear)
router.get("/:enterpriseId/technology/softwares/:softwareId/update-managements/filter/by-current-month", updateManagementController.getUpdateManagementsByCurrentMonth)
router.get("/:enterpriseId/technology/softwares/:softwareId/update-managements/filter/by-current-week", updateManagementController.getUpdateManagementsByCurrentWeek)
router.get("/:enterpriseId/technology/softwares/:softwareId/update-managements/filter/by-current-date", updateManagementController.getUpdateManagementsByCurrentDate)
router.post("/:enterpriseId/technology/softwares/:softwareId/add-support", supportController.addSupport)
router.get("/:enterpriseId/technology/softwares/:softwareId/supports/:supportId", supportController.getSupport)
router.get("/:enterpriseId/technology/softwares/:softwareId/supports/", supportController.getAllSupports)
router.put("/:enterpriseId/technology/softwares/:softwareId/supports/update-support/:supportId", supportController.updateSupport)
router.delete("/:enterpriseId/technology/softwares/:softwareId/supports/delete-support/:supportId", supportController.deleteSupport)
router.delete("/:enterpriseId/technology/softwares/:softwareId/supports/delete-all", supportController.deleteAllSuports)
router.get("/:enterpriseId/technology/softwares/:softwareId/supports/filter/by-custom-date", supportController.getSupportsByCustomDate)
router.get("/:enterpriseId/technology/softwares/:softwareId/supports/filter/by-current-year", supportController.getSupportsByCurrentYear)
router.get("/:enterpriseId/technology/softwares/:softwareId/supports/filter/by-current-month", supportController.getSupportsByCurrentMonth)
router.get("/:enterpriseId/technology/softwares/:softwareId/supports/filter/by-current-week", supportController.getSupportsByCurrentWeek)
router.get("/:enterpriseId/technology/softwares/:softwareId/supports/filter/by-current-date", supportController.getSupportsByCurrentDate)
router.get("/:enterpriseId/technology/softwares/:softwareId/supports/filter/by-priority", supportController.getSupportsByPriority)
router.get("/:enterpriseId/technology/softwares/:softwareId/supports/filter/by-type-support", supportController.getSupportByTypeSupport)
router.post("/:enterpriseId/technology/softwares/:softwareId/add-license-management", licenseManagementController.addLicenseManagement)
router.get("/:enterpriseId/technology/softwares/:softwareId/license-managements/:licenseManagementId", licenseManagementController.getLicenseManagement)
router.get("/:enterpriseId/technology/softwares/:softwareId/license-managements", licenseManagementController.getAllLicenseManagements)
router.put("/:enterpriseId/technology/softwares/:softwareId/license-managements/update-license-management/:licenseManagementId", licenseManagementController.updateLicenseManagement)
router.delete("/:enterpriseId/technology/softwares/:softwareId/license-managements/delete-license-management/:licenseManagementId", licenseManagementController.deleteLicenseManagement)
router.delete("/:enterpriseId/technology/softwares/:softwareId/license-managements/delete-all", licenseManagementController.deleteAllLicenseManagements)
router.get("/:enterpriseId/technology/softwares/:softwareId/license-managements/filter/by-custom-date", licenseManagementController.getLicenseManagementsByCustomDate)
router.get("/:enterpriseId/technology/softwares/:softwareId/license-managements/filter/by-current-year", licenseManagementController.getLicenseManagementsByCurrentYear)
router.get("/:enterpriseId/technology/softwares/:softwareId/license-managements/filter/by-current-month", licenseManagementController.getLicenseManagementsByCurrentMonth)
router.get("/:enterpriseId/technology/softwares/:softwareId/license-managements/filter/by-current-week", licenseManagementController.getLicenseManagementsByCurrentWeek)
router.get("/:enterpriseId/technology/softwares/:softwareId/license-managements/filter/by-current-date", licenseManagementController.getLicenseManagementsByCurrentDate)
router.get("/:enterpriseId/technology/softwares/:softwareId/license-managements/filter/by-expiration-date", licenseManagementController.getLicenseManagementsByExpirationDate)
router.get("/:enterpriseId/technology/softwares/:softwareId/license-managements/filter/by-type-license", licenseManagementController.getLicenseManagementsByTypeLicense)
router.post("/:enterpriseId/technology/softwares/:softwareId/add-security-update", securityUpdateController.addSecurityUpdate)
router.get("/:enterpriseId/technology/softwares/:softwareId/security-updates/:securityUpdateId", securityUpdateController.getSecurityUpdate)
router.get("/:enterpriseId/technology/softwares/:softwareId/security-updates/", securityUpdateController.getAllSecurityUpdates)
router.put("/:enterpriseId/technology/softwares/:softwareId/security-updates/update-security-update/:securityUpdateId", securityUpdateController.updateSecurityUpdate)
router.delete("/:enterpriseId/technology/softwares/:softwareId/security-updates/delete-security-update/:securityUpdateId", securityUpdateController.deleteSecurityUpdate)
router.delete("/:enterpriseId/technology/softwares/:softwareId/security-updates/delete-all", securityUpdateController.deleteAllSecurityUpdates)
router.get("/:enterpriseId/technology/softwares/:softwareId/security-updates/filter/by-custom-date", securityUpdateController.getSecurityUpdatesByCustomDate)
router.get("/:enterpriseId/technology/softwares/:softwareId/security-updates/filter/by-current-year", securityUpdateController.getSecurityUpdatesByCurrentYear)
router.get("/:enterpriseId/technology/softwares/:softwareId/security-updates/filter/by-current-month", securityUpdateController.getSecurityUpdatesByCurrentMonth)
router.get("/:enterpriseId/technology/softwares/:softwareId/security-updates/filter/by-current-week", securityUpdateController.getSecurityUpdatesByCurrentWeek)
router.get("/:enterpriseId/technology/softwares/:softwareId/security-updates/filter/by-current-date", securityUpdateController.getSecurityUpdatesByCurrentDate)

module.exports = router