const express = require("express")
const router = express.Router()
const authMiddleware = require("../middlewares/userMiddlewares/authMiddleware")
const userController = require("../controllers/userController")
const passwordValidator = require("../middlewares/userMiddlewares/security/passwords/passwordMiddleware")
const passwordUpdatedValidator = require("../middlewares/userMiddlewares/security/passwords/passwordUpdatedMiddleware")
const verifyTwoFA = require("../middlewares/userMiddlewares/2FA/2FAVerifyMiddleware")
const verifyRegistration2FA = require("../middlewares/userMiddlewares/2FA/2FAActivateUser")
const setDeleteAccountOfUser = require("../controllers/handlers/security/userInfo/setChangesOfUser")

router.post("/register", userController.registerUser)
router.post("/verify-register", verifyRegistration2FA)
router.post("/login", userController.loginUser)
router.post("/login-with-recovery-key", userController.loginWithRecoveryKey)
router.post("/verify-2fa", verifyTwoFA)
router.post("/logout", authMiddleware, userController.logoutUser)
router.get("/:userId", authMiddleware, userController.getUserInfo)
router.get("/get-user/by-email", userController.getUserByEmail)
router.get("/:userId/logs", authMiddleware, userController.getLogs)
router.put("/:userId/update", authMiddleware, userController.updateUser)
router.post("/:userId/delete", authMiddleware, userController.deleteUser)
router.post("/:userId/confirm-delete-account", authMiddleware, setDeleteAccountOfUser)
router.post("/:userId/update-password", passwordUpdatedValidator, authMiddleware, userController.updatePassword)
router.get("/:userId/devices", authMiddleware, userController.getDevices)
router.post("/:userId/validate-password", authMiddleware, userController.validatePassword)
router.post("/forgot-password", userController.forgotPassword)
router.post("/:userId/set-new-password", authMiddleware, userController.setPasswordBecauseForgot)
router.post("/:userId/update-retention-data", authMiddleware, userController.updateRetentionData)

module.exports = router