require("dotenv").config()
//intancias de crear servidor
const express = require("express")
const useragent = require("express-useragent")
const app = express()
const http = require("http")
const server = http.createServer(app)
const cookieParser = require("cookie-parser")
const bodyParser = require("body-parser")
const cors = require("cors")
const morgan = require("morgan")
const connectDB = require("./config/db")
const PORT = process.env.PORT || 3000
const userRoutes = require("./routes/userRoutes")
const enterpriseRoutes = require("./routes/enterpriseRoutes")
const financeRoutes = require("./routes/financeRoutes")
const supplierRoutes = require("./routes/supplierRoutes")
const clientRoutes = require("./routes/clientRoutes")
const projectRoutes = require("./routes/projectRoutes")
//rrhh
const rrhhRoutes = require("./routes/rrhhRoutes/rrhhRoutes")
const employeeRoutes = require("./routes/rrhhRoutes/employeesRoutes")
const RRHHObjectiveRoutes = require('./routes/rrhhRoutes/RRHHObjectives/rrhhObjectivesRoutes')
const classificationRoutes = require('./routes/rrhhRoutes/RRHHObjectives/classificationRoutes')
const assistRoutes = require("./routes/rrhhRoutes/assistsRoutes")
const liquidationRoutes = require("./routes/rrhhRoutes/liquidationsRoutes")
const accidentRoutes = require("./routes/rrhhRoutes/accidentsRoutes")
const syndicateRoutes = require("./routes/rrhhRoutes/syndicatesRoutes")
const cctRoutes = require("./routes/rrhhRoutes/cctsRoutes")
const surveyRoutes = require("./routes/rrhhRoutes/satisfaction/surveyRoutes")
const weightRoutes = require("./routes/rrhhRoutes/satisfaction/weightRoutes")
const artRoutes = require("./routes/rrhhRoutes/artsRoutes")
const departmentRoutes = require("./routes/rrhhRoutes/departmentRoutes")
const banksRoutes = require("./routes/rrhhRoutes/banksRoutes")
const sustainableEmployeeRoutes = require("./routes/sustainableRrhhRoutes")
const technologyRoutes = require("./routes/technologyRoutes")
const sustainableEnterpriseRoutes = require("./routes/sustainableEnterpriseRoutes")
const memberRoutes = require("./routes/memberRoutes")
const uxUserRoutes = require("./routes/uxUserRoutes")
const deviceRoutes = require("./routes/deviceRoutes")
const securityRoutes = require("./routes/securityRoutes")
const { scheduleProjectReminder, scheduleTaskOfProjectReminder } = require("./controllers/handlers/projects/alertScheduler")
const memberRequestWarning = require("./controllers/handlers/members/memberRequestWarning")
const setNotificationAudit = require("./controllers/handlers/sustainable/audits/setNotificationAudit")
const scheduleCronWorkEnvironmentSnapshot = require("./controllers/handlers/rrhh/employees/scheduleCronWorkEnvironmentSnapshots")
const cronRRHHObjectives = require('./controllers/handlers/rrhh/objectives/health/cronRRHHObjective')
const cronRRHHObjectiveProgressSnapshot = require('./controllers/handlers/rrhh/objectives/snapshots/progressSnapshot/cronRRHHObjectiveProgressSnapshot')
const cronRRHHObjectiveSnapshot = require('./controllers/handlers/rrhh/objectives/snapshots/objective/cronRRHHObjectiveSnapshot')
//const inactivityUserWarnToDelete = require("./controllers/handlers/security/data/inactivityUserWarnToDelete")

//recordatorio proyectos

const startServer = async () => {

    scheduleCronWorkEnvironmentSnapshot()
    scheduleProjectReminder()
    scheduleTaskOfProjectReminder()
    cronRRHHObjectiveProgressSnapshot()
    cronRRHHObjectives()
    cronRRHHObjectiveSnapshot()
    memberRequestWarning()
    setNotificationAudit()
    //inactivityUserWarnToDelete()
    app.use(cookieParser())
    //usos esenciales
    await connectDB()
    app.use(cors({
        origin: "http://localhost:4200",
        credentials: true
    }))
    app.use(useragent.express())
    app.use(morgan("dev"))
    app.use(bodyParser.urlencoded({ extended: true }))
    app.use(bodyParser.json())
    app.use("/", userRoutes)
    app.use("/", enterpriseRoutes)
    app.use("/", financeRoutes)
    app.use("/", supplierRoutes)
    app.use("/", clientRoutes)
    app.use("/", projectRoutes)
    //rrhh
    app.use("/", rrhhRoutes)
    app.use("/", employeeRoutes)
    app.use('/', RRHHObjectiveRoutes)
    app.use('/', classificationRoutes)
    app.use("/", assistRoutes)
    app.use("/", liquidationRoutes)
    app.use("/", accidentRoutes)
    app.use("/", syndicateRoutes)
    app.use("/", cctRoutes)
    app.use("/", surveyRoutes)
    app.use("/", weightRoutes)
    app.use("/", artRoutes)
    app.use('/', departmentRoutes)
    app.use("/", banksRoutes)
    app.use("/", sustainableEmployeeRoutes)
    app.use("/", technologyRoutes)
    app.use("/", sustainableEnterpriseRoutes)
    app.use("/", enterpriseRoutes)
    app.use("/", memberRoutes)
    app.use("/", uxUserRoutes)
    app.use("/", deviceRoutes)
    app.use("/", securityRoutes)

    server.listen(PORT, () => {
        console.log(`GreenTeccnia+. Servidor escuchando en ${PORT}`);
    })
}

startServer()